Sound Settings:
  Button clicked: "UI_BUTTON_CLICK"
  Open shop: "BLOCK_NOTE_BLOCK_PLING"
  Item purchased: "ENTITY_EXPERIENCE_ORB_PICKUP"

Messages:
  Shop has been created: "&aShop &e{shopName} &ahas been created."
  Shop has been deleted: "&aShop &e{shopName} &ahas been deleted."
  Shop already exists: "&cA shop with the specified name already exists."
  Shop does not exist: "&cThe specified shop does not exist."
  Shop list title: "&aList of all existing shops:"
  Shop name exceeds the length limit: "&cThe length of the shop name has exceeded the limit of 15."
  Shop size not specified: "&cPlease specify the size of the shop."
  Invalid arguments: "&cInvalid arguments. Please try again."
  Invalid size input: "&cThe size must be a multiple of 9 and within the range of 9 to 54."
  Invalid price: "&cInvalid price. Please try again."
  Insufficient funds: "&cYou don't have enough money to purchase this item."
  Inventory full: "&cYou don't have enough space in your inventory."
  Item purchased: "&aYou have purchased &e{amount}x {itemName} &afor &e${price}&a."
  Request price input: "&aPlease enter the price or type 'cancel' to exit."
  No permissions: "&cYou do not have the required permission to execute this command."
  Player not found: "&cThe player is currently offline."
  Price has been set: "&aThe price has been set to §e{price}§a."
  Price input cancelled: "&aCancelled!"
  Price input exceeds the limit: "&cThe price input has exceeded the limit of &e2,147,483,647&c."

Formats:
  Shops in list: "&6- &aShop: &e{shopName} &aSize: &e{size}"
  Confirm button name: "&aConfirm"
  Confirm purchase: "&aClick again to confirm purchase"
  Item lore:
    - "&7----------------"
    - "&ePrice: &a{price}"
    - "&eAmount: &a{amount}"